export const initialPlayers = [
  {
    "id": "u1777778844551-0",
    "initials": "AT",
    "avatar": "linear-gradient(135deg,#64748b 0%,#334155 100%)",
    "name": "Alex Turner",
    "email": "alex@example.com",
    "gender": "M",
    "age": 34,
    "date": "5/2/2026",
    "phone": "(512) 555-0100",
    "partner": "Sam Lee",
    "partnerId": null,
    "division": "MXD 14.0",
    "dupr": "4.20",
    "paid": "✓ Paid",
    "paidClass": "pill-approved",
    "status": "✓ Confirmed",
    "statusClass": "pill-approved"
  },
  {
    "id": "p5",
    "initials": "DR",
    "avatar": "linear-gradient(135deg,#f59e0b 0%,#92400e 100%)",
    "name": "Diego Riverasssssssss",
    "email": "d.rivera.atx@yahoo.com",
    "gender": "F",
    "age": 42,
    "date": "04/06/2026",
    "phone": "(512) 555-0177",
    "partner": "Linda T.",
    "partnerId": null,
    "division": "MXD 18.0",
    "dupr": "4.71",
    "paid": "◐ Partial",
    "paidClass": "pill-pending",
    "status": "✓ Confirmed",
    "statusClass": "pill-approved"
  },
  {
    "id": "p1",
    "initials": "JM",
    "avatar": "linear-gradient(135deg,#aaff00 0%,#5a8a00 100%)",
    "name": "Jorge Martinez",
    "email": "jorge.martinez@gmail.com",
    "gender": "M",
    "age": 34,
    "date": "04/02/2026",
    "phone": "(512) 555-0188",
    "partner": "Sarah C.",
    "partnerId": "p2",
    "division": "MXD 14.0",
    "dupr": "5.02",
    "paid": "✓ Paid",
    "paidClass": "pill-approved",
    "status": "✓ Confirmed",
    "statusClass": "pill-approved"
  },
  {
    "id": "p2",
    "initials": "SC",
    "avatar": "linear-gradient(135deg,#f472b6 0%,#9d2466 100%)",
    "name": "Sarah Chen",
    "email": "sarah.chen.tx@gmail.com",
    "gender": "F",
    "age": 31,
    "date": "04/02/2026",
    "phone": "(713) 555-0142",
    "partner": "Jorge M.",
    "partnerId": "p1",
    "division": "MXD 12.0",
    "dupr": "4.78",
    "paid": "✓ Paid",
    "paidClass": "pill-approved",
    "status": "✓ Confirmed",
    "statusClass": "pill-approved"
  },
  {
    "id": "p9",
    "initials": "LM",
    "avatar": "linear-gradient(135deg,#f43f5e 0%,#881337 100%)",
    "name": "Laura Mitchell",
    "email": "laura.mitchell@gmail.com",
    "gender": "F",
    "age": 26,
    "date": "05/01/2026",
    "phone": "(214) 555-0312",
    "partner": "Chris T.",
    "partnerId": null,
    "division": "MXD 12.0",
    "dupr": "4.32",
    "paid": "✓ Paid",
    "paidClass": "pill-approved",
    "status": "✓ Confirmed",
    "statusClass": "pill-approved"
  },
  {
    "id": "p10",
    "initials": "RK",
    "avatar": "linear-gradient(135deg,#06b6d4 0%,#0e4f6b 100%)",
    "name": "Ryan Kowalski",
    "email": "r.kowalski@outlook.com",
    "gender": "M",
    "age": 44,
    "date": "05/01/2026",
    "phone": "(832) 555-0478",
    "partner": "Laura M.",
    "partnerId": null,
    "division": "MXD 16.0",
    "dupr": "5.11",
    "paid": "★ Comp",
    "paidClass": "pill-comp",
    "status": "⏳ Pending",
    "statusClass": "pill-pending"
  },
  {
    "id": "p11",
    "initials": "NB",
    "avatar": "linear-gradient(135deg,#8b5cf6 0%,#3b0764 100%)",
    "name": "Nadia Brooks",
    "email": "nadia.brooks99@yahoo.com",
    "gender": "F",
    "age": 22,
    "date": "05/02/2026",
    "phone": "(512) 555-0655",
    "partner": "None",
    "partnerId": null,
    "division": "MXD 14.0",
    "dupr": "4.44",
    "paid": "◐ Partial",
    "paidClass": "pill-pending",
    "status": "⏳ Pending",
    "statusClass": "pill-pending"
  }
];
